"use client";

import { useEffect, useRef, useState } from "react";

interface ApiResponse {
  available: boolean;
  commentary: string | null;
  asOf?: string;
  ageMs?: number;
  nextRefreshMs?: number;
  mode?: "live" | "no-sig" | "no-chg" | "off";
  score?: number;
  headlineCount?: number;
  warning?: string;
  reason?: string;
  tokenUsage?: { input: number; output: number };
}

const FOREGROUND_REFRESH_MS = 5 * 60_000;
const BACKGROUND_REFRESH_MS = 30 * 60_000;

/**
 * "오늘의 시장 메모" — a single Korean paragraph generated by Claude from
 * the F&G score, components, and Yahoo Finance headlines. Refreshes every
 * 5min in foreground; the actual commentary only changes when the input
 * signature shifts (server-side decision).
 *
 * Renders nothing if the API key isn't configured server-side.
 */
export function SentimentCommentary() {
  const [data, setData] = useState<ApiResponse | null>(null);
  const inFlight = useRef(false);
  const [hidden, setHidden] = useState(false);

  useEffect(() => {
    let cancelled = false;
    let timer: ReturnType<typeof setTimeout> | null = null;

    async function load() {
      if (inFlight.current) return;
      inFlight.current = true;
      try {
        const res = await fetch("/api/sentiment-commentary", {
          cache: "no-store",
        });
        const json = (await res.json()) as ApiResponse;
        if (cancelled) return;
        if (!json.available) {
          setHidden(true);
        } else {
          setData(json);
        }
      } catch {
        // silent — we'd rather hide than show a broken card
      } finally {
        inFlight.current = false;
      }
    }

    function schedule() {
      if (timer) clearTimeout(timer);
      const wait =
        typeof document !== "undefined" && document.hidden
          ? BACKGROUND_REFRESH_MS
          : FOREGROUND_REFRESH_MS;
      timer = setTimeout(async () => {
        await load();
        if (!cancelled) schedule();
      }, wait);
    }

    function onVis() {
      if (typeof document === "undefined" || document.hidden) return;
      load().finally(() => {
        if (!cancelled) schedule();
      });
    }

    load().finally(() => {
      if (!cancelled) schedule();
    });

    if (typeof document !== "undefined") {
      document.addEventListener("visibilitychange", onVis);
    }
    return () => {
      cancelled = true;
      if (timer) clearTimeout(timer);
      if (typeof document !== "undefined") {
        document.removeEventListener("visibilitychange", onVis);
      }
    };
  }, []);

  if (hidden) return null;
  if (!data || !data.commentary) {
    return (
      <div className="rounded-md border border-dashed border-border bg-bg-subtle/30 px-3 py-2 text-[11px] text-ink-dim">
        시장 메모 생성 중…
      </div>
    );
  }

  const ageMin = data.ageMs ? Math.floor(data.ageMs / 60_000) : 0;
  const ageLabel =
    data.ageMs && data.ageMs > 0 ? `${ageMin}m 전 갱신` : "방금 갱신";

  return (
    <div className="rounded-md border border-accent/30 bg-accent/5 px-3 py-2.5">
      <div className="mb-1 flex items-center justify-between gap-2 text-[10px] font-semibold uppercase tracking-wider text-accent">
        <span>오늘의 시장 메모 · Claude</span>
        <span className="font-normal normal-case text-ink-dim">
          {ageLabel}
          {data.mode === "no-chg" ? " · 변화 없음" : ""}
          {data.mode === "no-sig" ? " · 시그널 동일" : ""}
        </span>
      </div>
      <p className="text-[12px] leading-relaxed text-ink">{data.commentary}</p>
    </div>
  );
}
